In [10]:
import pandas as pd

df = pd.read_csv(r'C:\Users\alexa\OneDrive\Documents\Careers\Freelance\Amazon Project\Amazon-orders.csv')
df.head()

,Order Date,Order ID,Payment Instrument Type,Website,Purchase Order Number,Ordering Customer Email,Shipment Date,Shipping Address Name,Shipping Address Street 1,Shipping Address Street 2,...,Order Status,Carrier Name & Tracking Number,Subtotal,Shipping Charge,Tax Before Promotions,Total Promotions,Tax Charged,Total Charged,Buyer Name,Group Name
0,8/27/2019,112-7183488-5834633,MasterCard - 6936,Amazon.com,NaN,alago@villanova.edu,8/27/2019,Athena Lago,VU BOX 8545 VILLANOVA UNIVERSITY,800 E LANCASTER AVE,...,Shipped,UPS(1Z21F58E0378257234),$57.75,$0.00,$3.46,$0.00,$3.46,$61.21,Athena Lago,NaN
1,8/27/2019,112-7183488-5834633,MasterCard - 6936,Amazon.com,NaN,alago@villanova.edu,8/28/2019,Athena Lago,VU BOX 8545 VILLANOVA UNIVERSITY,800 E LANCASTER AVE,...,Shipped,AMZN_US(TBA747033167000),$43.49,$0.00,$2.61,$0.00,$2.61,$46.10,Athena Lago,NaN
2,1/14/2020,112-6388508-8419469,MasterCard - 8476,Amazon.com,NaN,alago@villanova.edu,1/14/2020,Athena Lago,VU BOX 8545 VILLANOVA UNIVERSITY,800 E LANCASTER AVE,...,Shipped,AMZN_US(TBA671170261000),$8.99,$0.00,$0.54,$0.00,$0.54,$9.53,Athena Lago,NaN
3,1/21/2020,112-2583050-5347400,MasterCard - 8476,Amazon.com,NaN,alago@villanova.edu,1/21/2020,Athena Lago,VU BOX 8545 VILLANOVA UNIVERSITY,800 E LANCASTER AVE,...,Shipped,AMZN_US(TBAACY503012255),$17.16,$0.00,$1.03,$0.00,$1.03,$18.19,Athena Lago,NaN
4,2/2/2020,111-6269212-4166636,MasterCard - 6936 and Gift Certificate/Card,Amazon.com,NaN,alago@villanova.edu,2/2/2020,Athena Lago,25 COOLIDGE AVE,NaN,...,Shipped,USPS(9341989714090419647195),$12.49,$0.00,$0.83,$0.00,$0.83,$13.32,Athena Lago,NaN

In [12]:
df.shape

(57, 23)

In [14]:
df = df.fillna(0)
df.head()

,Order Date,Order ID,Payment Instrument Type,Website,Purchase Order Number,Ordering Customer Email,Shipment Date,Shipping Address Name,Shipping Address Street 1,Shipping Address Street 2,...,Order Status,Carrier Name & Tracking Number,Subtotal,Shipping Charge,Tax Before Promotions,Total Promotions,Tax Charged,Total Charged,Buyer Name,Group Name
0,8/27/2019,112-7183488-5834633,MasterCard - 6936,Amazon.com,0.0,alago@villanova.edu,8/27/2019,Athena Lago,VU BOX 8545 VILLANOVA UNIVERSITY,800 E LANCASTER AVE,...,Shipped,UPS(1Z21F58E0378257234),$57.75,$0.00,$3.46,$0.00,$3.46,$61.21,Athena Lago,0.0
1,8/27/2019,112-7183488-5834633,MasterCard - 6936,Amazon.com,0.0,alago@villanova.edu,8/28/2019,Athena Lago,VU BOX 8545 VILLANOVA UNIVERSITY,800 E LANCASTER AVE,...,Shipped,AMZN_US(TBA747033167000),$43.49,$0.00,$2.61,$0.00,$2.61,$46.10,Athena Lago,0.0
2,1/14/2020,112-6388508-8419469,MasterCard - 8476,Amazon.com,0.0,alago@villanova.edu,1/14/2020,Athena Lago,VU BOX 8545 VILLANOVA UNIVERSITY,800 E LANCASTER AVE,...,Shipped,AMZN_US(TBA671170261000),$8.99,$0.00,$0.54,$0.00,$0.54,$9.53,Athena Lago,0.0
3,1/21/2020,112-2583050-5347400,MasterCard - 8476,Amazon.com,0.0,alago@villanova.edu,1/21/2020,Athena Lago,VU BOX 8545 VILLANOVA UNIVERSITY,800 E LANCASTER AVE,...,Shipped,AMZN_US(TBAACY503012255),$17.16,$0.00,$1.03,$0.00,$1.03,$18.19,Athena Lago,0.0
4,2/2/2020,111-6269212-4166636,MasterCard - 6936 and Gift Certificate/Card,Amazon.com,0.0,alago@villanova.edu,2/2/2020,Athena Lago,25 COOLIDGE AVE,0,...,Shipped,USPS(9341989714090419647195),$12.49,$0.00,$0.83,$0.00,$0.83,$13.32,Athena Lago,0.0

In [15]:
df["Total Charged"] = df["Total Charged"].str.replace('$','').astype(float)
df.head()

<ipython-input-15-8608fa0e0747>:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will*not* be treated as literal strings when regex=True.
  df["Total Charged"] = df["Total Charged"].str.replace('$','').astype(float)

,Order Date,Order ID,Payment Instrument Type,Website,Purchase Order Number,Ordering Customer Email,Shipment Date,Shipping Address Name,Shipping Address Street 1,Shipping Address Street 2,...,Order Status,Carrier Name & Tracking Number,Subtotal,Shipping Charge,Tax Before Promotions,Total Promotions,Tax Charged,Total Charged,Buyer Name,Group Name
0,8/27/2019,112-7183488-5834633,MasterCard - 6936,Amazon.com,0.0,alago@villanova.edu,8/27/2019,Athena Lago,VU BOX 8545 VILLANOVA UNIVERSITY,800 E LANCASTER AVE,...,Shipped,UPS(1Z21F58E0378257234),$57.75,$0.00,$3.46,$0.00,$3.46,61.21,Athena Lago,0.0
1,8/27/2019,112-7183488-5834633,MasterCard - 6936,Amazon.com,0.0,alago@villanova.edu,8/28/2019,Athena Lago,VU BOX 8545 VILLANOVA UNIVERSITY,800 E LANCASTER AVE,...,Shipped,AMZN_US(TBA747033167000),$43.49,$0.00,$2.61,$0.00,$2.61,46.10,Athena Lago,0.0
2,1/14/2020,112-6388508-8419469,MasterCard - 8476,Amazon.com,0.0,alago@villanova.edu,1/14/2020,Athena Lago,VU BOX 8545 VILLANOVA UNIVERSITY,800 E LANCASTER AVE,...,Shipped,AMZN_US(TBA671170261000),$8.99,$0.00,$0.54,$0.00,$0.54,9.53,Athena Lago,0.0
3,1/21/2020,112-2583050-5347400,MasterCard - 8476,Amazon.com,0.0,alago@villanova.edu,1/21/2020,Athena Lago,VU BOX 8545 VILLANOVA UNIVERSITY,800 E LANCASTER AVE,...,Shipped,AMZN_US(TBAACY503012255),$17.16,$0.00,$1.03,$0.00,$1.03,18.19,Athena Lago,0.0
4,2/2/2020,111-6269212-4166636,MasterCard - 6936 and Gift Certificate/Card,Amazon.com,0.0,alago@villanova.edu,2/2/2020,Athena Lago,25 COOLIDGE AVE,0,...,Shipped,USPS(9341989714090419647195),$12.49,$0.00,$0.83,$0.00,$0.83,13.32,Athena Lago,0.0

In [16]:
df["Total Charged"].sum()

1603.98

In [17]:
df["Total Charged"].mean()

28.140000000000004

In [18]:
df["Total Charged"].median()

17.99

In [20]:
df["Total Charged"].max()

95.09

In [21]:
df["Total Charged"].min()

5.29

In [22]:
df["Tax Charged"] = df["Tax Charged"].str.replace('$','').astype(float)

df.head()

<ipython-input-22-0147bda9d2ad>:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will*not* be treated as literal strings when regex=True.
  df["Tax Charged"] = df["Tax Charged"].str.replace('$','').astype(float)

,Order Date,Order ID,Payment Instrument Type,Website,Purchase Order Number,Ordering Customer Email,Shipment Date,Shipping Address Name,Shipping Address Street 1,Shipping Address Street 2,...,Order Status,Carrier Name & Tracking Number,Subtotal,Shipping Charge,Tax Before Promotions,Total Promotions,Tax Charged,Total Charged,Buyer Name,Group Name
0,8/27/2019,112-7183488-5834633,MasterCard - 6936,Amazon.com,0.0,alago@villanova.edu,8/27/2019,Athena Lago,VU BOX 8545 VILLANOVA UNIVERSITY,800 E LANCASTER AVE,...,Shipped,UPS(1Z21F58E0378257234),$57.75,$0.00,$3.46,$0.00,3.46,61.21,Athena Lago,0.0
1,8/27/2019,112-7183488-5834633,MasterCard - 6936,Amazon.com,0.0,alago@villanova.edu,8/28/2019,Athena Lago,VU BOX 8545 VILLANOVA UNIVERSITY,800 E LANCASTER AVE,...,Shipped,AMZN_US(TBA747033167000),$43.49,$0.00,$2.61,$0.00,2.61,46.10,Athena Lago,0.0
2,1/14/2020,112-6388508-8419469,MasterCard - 8476,Amazon.com,0.0,alago@villanova.edu,1/14/2020,Athena Lago,VU BOX 8545 VILLANOVA UNIVERSITY,800 E LANCASTER AVE,...,Shipped,AMZN_US(TBA671170261000),$8.99,$0.00,$0.54,$0.00,0.54,9.53,Athena Lago,0.0
3,1/21/2020,112-2583050-5347400,MasterCard - 8476,Amazon.com,0.0,alago@villanova.edu,1/21/2020,Athena Lago,VU BOX 8545 VILLANOVA UNIVERSITY,800 E LANCASTER AVE,...,Shipped,AMZN_US(TBAACY503012255),$17.16,$0.00,$1.03,$0.00,1.03,18.19,Athena Lago,0.0
4,2/2/2020,111-6269212-4166636,MasterCard - 6936 and Gift Certificate/Card,Amazon.com,0.0,alago@villanova.edu,2/2/2020,Athena Lago,25 COOLIDGE AVE,0,...,Shipped,USPS(9341989714090419647195),$12.49,$0.00,$0.83,$0.00,0.83,13.32,Athena Lago,0.0

In [23]:
df["Tax Charged"].sum()

70.64

In [24]:
df["Tax Charged"].sum()/df["Total Charged"].sum()

0.044040449382161874